Added alternative for ImageReflectionView with enhanced ReflectionVie…
sparrow007/CarouselRecyclerview pull request #4
Opened 2021-04-09 10:36 UTC by snehilrx

Implemented a custom linear layout to show reflection of the view contained in it. 
Feature 👍🏾 
10x faster load time than  ReflectionImageView
Matches the view draw in real time.

2021-04-09 19:59 UTC, sparrow007 commented
@snehilrx Thank you for the pull request but before merge into master please add the package name at the top of the file because if that's not added it keeps generating the error of inflation.

2021-04-10 21:02 UTC, sparrow007 requested changes

2021-04-10 21:02 UTC, sparrow007 commented on carouselrecyclerview/src/main/java/com/jackandphantom/carouselrecyclerview/view/ReflectionViewContainer.kt
> +            R.styleable.ReflectionViewContainer,
Hi, @snehilrx  I don't see this styleable in attrs.xml, so which style you are using here?

2021-04-10 21:04 UTC, snehilrx commented
@sparrow007 I had fixed all the issue as mentioned by you and also the issues that I had found.

Here is a sample usage
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.jackandphantom.carouselrecyclerview.view.ReflectionViewContainer
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:android="http://schemas.android.com/apk/res/android"
    app:reflect_relativeDepth="0.5"
    app:reflect_gap="0dp"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    >
    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/guypro"
        android:scaleType="fitXY"
        android:id="@+id/image" />
</com.jackandphantom.carouselrecyclerview.view.ReflectionViewContainer>
```


<p>
<img width=400 src="https://user-images.githubusercontent.com/7668602/114284225-14244980-9a6c-11eb-8e49-aa7b191a6d1d.png"/>
</p>

Sample Screen
<img width=400 src="https://user-images.githubusercontent.com/7668602/114284305-9a409000-9a6c-11eb-9cdf-ec2f1c82eac3.gif"/>

2021-04-10 21:12 UTC, sparrow007 commented
Yeah I see and I love what you do (awesome work man), but if you see your files changes currently which have some error because of different commits (as I mentioned above) so I can't merge it would you please create another pull with all new changes so that it will very easy for me to merge.

2021-04-10 21:18 UTC, snehilrx commented
Going to sleep. Goodnight. I will clarify things tomorrow.

2021-04-10 21:20 UTC, sparrow007 commented
Yeah, no problem :)

2021-04-14 01:51 UTC, snehilrx commented
Sorry for the delayed fix, I was busy with some work. I think it should work now.

2021-04-14 01:54 UTC, sparrow007 commented
No problem, thanks i am reviewing the codes now :)

2021-04-14 02:09 UTC, sparrow007 commented
LGTM

2021-04-14 02:10 UTC, sparrow007 approved these changes

2021-04-14 02:11 UTC, merged